import { describe, expect, it, vi } from "vitest";
import {
  businessProject,
  material,
  party,
  projectSite,
  projectSiteComplianceSummary,
  projectSiteInvestmentSummary,
  projectSiteKitchenEquipment,
  projectSiteKitchenEquipmentChangeRequest,
  projectUsageRequest,
  warehouse,
} from "./appTestHelpers";
import {
  buildExternalProjectSiteWorkspaceViewProps,
  buildProjectSitesHeadquartersViewProps,
} from "../src/components/project-sites/projectSitesViewModels";
import {
  createInitialIssueForm,
  createInitialKitchenEquipmentChangeForm,
  createInitialKitchenEquipmentForm,
  createInitialSiteForm,
  createInitialUsageForm,
} from "../src/components/project-sites/projectSiteFormState";

describe("projectSitesViewModels", () => {
  const projectUsageMaterial = {
    id: material.id,
    materialCode: material.materialCode,
    materialName: material.materialName,
    unit: material.projectSiteSaleUnit ?? material.baseUnit,
  };

  it("builds headquarters risk-ledger props without changing core callbacks or metrics", () => {
    const onSelectSite = vi.fn();
    const props = buildProjectSitesHeadquartersViewProps({
      sites: [projectSite],
      filteredSites: [projectSite],
      siteStatus: "ready",
      complianceSummaries: { [projectSite.id]: projectSiteComplianceSummary },
      usageRequests: [projectUsageRequest],
      filteredUsageRequests: [projectUsageRequest],
      usageStatus: "ready",
      materials: [projectUsageMaterial],
      warehouses: [warehouse],
      businessProjects: [businessProject],
      clientParties: [party],
      operatorParties: [party],
      subcontractorParties: [party],
      investmentSummary: projectSiteInvestmentSummary,
      investmentSummaryStatus: "ready",
      selectedInvestmentSiteId: projectSite.id,
      kitchenEquipment: [projectSiteKitchenEquipment],
      filteredKitchenEquipment: [projectSiteKitchenEquipment],
      filteredKitchenEquipmentChangeRequests: [projectSiteKitchenEquipmentChangeRequest],
      kitchenEquipmentStatus: "ready",
      query: "",
      usageFilter: "all",
      activeSiteCount: 1,
      pendingUsageCount: 1,
      totalRequestedQuantity: 2,
      totalIssuedQuantity: 1,
      pendingKitchenEquipmentChangeCount: 1,
      complianceBlockingIssueCount: 1,
      complianceWarningIssueCount: 2,
      canEditSites: true,
      canCreateUsage: true,
      canIssueUsage: true,
      masterStatus: "ready",
      openFormDrawer: null,
      selectedDetailSite: projectSite,
      selectedDetailSiteData: { usageRequests: [projectUsageRequest], kitchenEquipment: [projectSiteKitchenEquipment] },
      siteForm: createInitialSiteForm(),
      usageForm: createInitialUsageForm(),
      issueForm: createInitialIssueForm(),
      kitchenEquipmentForm: createInitialKitchenEquipmentForm(),
      kitchenEquipmentChangeForm: createInitialKitchenEquipmentChangeForm(),
      siteSubmitState: "idle",
      usageSubmitState: "idle",
      issueSubmitState: "idle",
      kitchenEquipmentSubmitState: "idle",
      kitchenEquipmentChangeSubmitState: "idle",
      siteSubmitError: "",
      usageSubmitError: "",
      issueSubmitError: "",
      kitchenEquipmentSubmitError: "",
      kitchenEquipmentChangeSubmitError: "",
      pendingIssueConfirm: false,
      onQueryChange: vi.fn(),
      onUsageFilterChange: vi.fn(),
      onOpenForm: vi.fn(),
      onSelectSite,
      onSelectedInvestmentSiteChange: vi.fn(),
      onSiteFormChange: vi.fn(),
      onUsageFormChange: vi.fn(),
      onIssueFormChange: vi.fn(),
      onKitchenEquipmentFormChange: vi.fn(),
      onKitchenEquipmentChangeFormChange: vi.fn(),
      onMaterialChange: vi.fn(),
      onCancelIssueConfirm: vi.fn(),
      onCloseForm: vi.fn(),
      onCloseDetail: vi.fn(),
      onCreateSite: vi.fn(),
      onCreateUsageRequest: vi.fn(),
      onIssueUsageRequest: vi.fn(),
      onCreateKitchenEquipment: vi.fn(),
      onCreateKitchenEquipmentChangeRequest: vi.fn(),
      onReviewKitchenEquipmentChangeRequest: vi.fn(),
      loadAttachments: vi.fn(),
      getAttachmentDownloadUrl: vi.fn(),
    });

    expect(props.filteredSites).toEqual([projectSite]);
    expect(props.complianceBlockingIssueCount).toBe(1);
    props.onSelectSite(projectSite);
    expect(onSelectSite).toHaveBeenCalledWith(projectSite);
  });

  it("builds external scoped portal props without exposing headquarters-only capabilities", () => {
    const props = buildExternalProjectSiteWorkspaceViewProps({
      portalSection: "insurance",
      sites: [projectSite],
      complianceSummaries: { [projectSite.id]: projectSiteComplianceSummary },
      pendingUsageCount: 1,
      pendingKitchenEquipmentChangeCount: 1,
      activeSiteCount: 1,
      totalRequestedQuantity: 2,
      totalIssuedQuantity: 1,
      kitchenEquipment: [projectSiteKitchenEquipment],
      filteredKitchenEquipment: [projectSiteKitchenEquipment],
      filteredKitchenEquipmentChangeRequests: [projectSiteKitchenEquipmentChangeRequest],
      kitchenEquipmentStatus: "ready",
      filteredUsageRequests: [projectUsageRequest],
      usageStatus: "ready",
      masterStatus: "ready",
      query: "",
      usageFilter: "all",
      openFormDrawer: null,
      canEditSites: false,
      canCreateUsage: true,
      canIssueUsage: false,
      usageForm: createInitialUsageForm(),
      kitchenEquipmentForm: createInitialKitchenEquipmentForm(),
      kitchenEquipmentChangeForm: createInitialKitchenEquipmentChangeForm(),
      warehouses: [warehouse],
      materials: [projectUsageMaterial],
      usageSubmitState: "idle",
      kitchenEquipmentSubmitState: "idle",
      kitchenEquipmentChangeSubmitState: "idle",
      usageSubmitError: "",
      kitchenEquipmentSubmitError: "",
      kitchenEquipmentChangeSubmitError: "",
      currentContactName: "项目经理",
      currentContactPhone: "13800000000",
      onSelectSection: vi.fn(),
      onOpenForm: vi.fn(),
      onQueryChange: vi.fn(),
      onUsageFilterChange: vi.fn(),
      onUsageFormChange: vi.fn(),
      onKitchenEquipmentFormChange: vi.fn(),
      onKitchenEquipmentChangeFormChange: vi.fn(),
      onMaterialChange: vi.fn(),
      onCloseForm: vi.fn(),
      onCreateUsageRequest: vi.fn(),
      onCreateKitchenEquipment: vi.fn(),
      onCreateKitchenEquipmentChangeRequest: vi.fn(),
      onReviewKitchenEquipmentChangeRequest: vi.fn(),
    });

    expect(props.portalSection).toBe("insurance");
    expect(props.canEditSites).toBe(false);
    expect(props.canIssueUsage).toBe(false);
    expect(props.sites).toEqual([projectSite]);
  });
});
