import { ExternalProjectSiteWorkspaceView } from "./project-sites/ExternalProjectSiteWorkspaceView";
import { ProjectSitesHeadquartersView } from "./project-sites/ProjectSitesHeadquartersView";
import {
  resolveProjectSitesWorkspaceProps,
  type ProjectSitesWorkspaceProps,
} from "./project-sites/projectSitesWorkspaceContract";
import { useProjectSitesData } from "./project-sites/useProjectSitesData";
import { useProjectSitesLoadDefaults } from "./project-sites/useProjectSitesLoadDefaults";
import { useProjectSiteMutations } from "./project-sites/useProjectSiteMutations";
import { useProjectSitesWorkspaceModel } from "./project-sites/useProjectSitesWorkspaceModel";
import { useProjectSitesWorkspaceState } from "./project-sites/useProjectSitesWorkspaceState";
import {
  buildExternalProjectSitePortalOptions,
  resolveProjectSitesWorkspacePermissions,
} from "./project-sites/projectSitesWorkspaceOptions";
import {
  buildExternalProjectSiteWorkspaceViewProps,
  buildProjectSitesHeadquartersViewProps,
} from "./project-sites/projectSitesViewModels";

export function ProjectSitesWorkspace(props: ProjectSitesWorkspaceProps) {
  const {
    loadProjectSites,
    loadUsageRequests,
    createProjectSite,
    createUsageRequest,
    issueUsageRequest,
    loadParties,
    loadMaterials,
    loadWarehouses,
    loadUsageOptions,
    loadBusinessProjects,
    loadInvestmentSummary,
    loadComplianceSummary,
    loadKitchenEquipment,
    loadKitchenEquipmentChangeRequests,
    loadUnifiedAttachments,
    getAttachmentDownloadUrl,
    createKitchenEquipment,
    createKitchenEquipmentChangeRequest,
    reviewKitchenEquipmentChangeRequest,
    canManage,
    canManageSites,
    canManageUsage,
    canIssue,
    usageOnly,
    portalSection,
    onPortalSectionChange,
    externalProjectSiteContactName,
    externalProjectSiteContactPhone,
  } = resolveProjectSitesWorkspaceProps(props);
  const permissions = resolveProjectSitesWorkspacePermissions({
    canManage,
    canManageSites,
    canManageUsage,
    canIssue,
  });
  const { canEditSites, canCreateUsage, canIssueUsage } = permissions;
  const {
    query,
    setQuery,
    usageFilter,
    setUsageFilter,
    selectedDetailSiteId,
    setSelectedDetailSiteId,
    openFormDrawer,
    setOpenFormDrawer,
    siteForm,
    setSiteForm,
    usageForm,
    setUsageForm,
    issueForm,
    setIssueForm,
    kitchenEquipmentForm,
    setKitchenEquipmentForm,
    kitchenEquipmentChangeForm,
    setKitchenEquipmentChangeForm,
    pendingIssueConfirm,
    setPendingIssueConfirm,
    closeFormDrawer,
  } = useProjectSitesWorkspaceState();

  const {
    onProjectSitesLoaded,
    onUsageRequestsLoaded,
    onMasterDataLoaded,
    onUsageOptionsLoaded,
    onKitchenEquipmentLoaded,
  } = useProjectSitesLoadDefaults({
    setUsageForm,
    setIssueForm,
    setKitchenEquipmentForm,
    setKitchenEquipmentChangeForm,
  });

  const {
    sites,
    setSites,
    usageRequests,
    setUsageRequests,
    parties,
    materials,
    warehouses,
    businessProjects,
    selectedInvestmentSiteId,
    setSelectedInvestmentSiteId,
    investmentSummary,
    investmentSummaryStatus,
    complianceSummaries,
    kitchenEquipment,
    setKitchenEquipment,
    kitchenEquipmentChangeRequests,
    setKitchenEquipmentChangeRequests,
    kitchenEquipmentStatus,
    setKitchenEquipmentStatus,
    siteStatus,
    usageStatus,
    masterStatus,
  } = useProjectSitesData({
    canEditSites,
    usageOnly,
    loadProjectSites,
    loadUsageRequests,
    loadParties,
    loadMaterials,
    loadWarehouses,
    loadUsageOptions,
    loadBusinessProjects,
    loadInvestmentSummary,
    loadComplianceSummary,
    loadKitchenEquipment,
    loadKitchenEquipmentChangeRequests,
    onProjectSitesLoaded,
    onUsageRequestsLoaded,
    onMasterDataLoaded,
    onUsageOptionsLoaded,
    onKitchenEquipmentLoaded,
  });

  const {
    siteSubmitState,
    usageSubmitState,
    issueSubmitState,
    kitchenEquipmentSubmitState,
    kitchenEquipmentChangeSubmitState,
    siteSubmitError,
    usageSubmitError,
    issueSubmitError,
    kitchenEquipmentSubmitError,
    kitchenEquipmentChangeSubmitError,
    handleCreateSite,
    handleCreateUsageRequest,
    handleIssueUsageRequest,
    handleCreateKitchenEquipment,
    handleCreateKitchenEquipmentChangeRequest,
    handleReviewKitchenEquipmentChangeRequest,
  } = useProjectSiteMutations({
    usageOnly,
    siteForm,
    usageForm,
    issueForm,
    kitchenEquipmentForm,
    kitchenEquipmentChangeForm,
    kitchenEquipment,
    createProjectSite,
    createUsageRequest,
    issueUsageRequest,
    createKitchenEquipment,
    createKitchenEquipmentChangeRequest,
    reviewKitchenEquipmentChangeRequest,
    loadKitchenEquipment,
    setSites,
    setUsageRequests,
    setIssueForm,
    setSiteForm,
    setUsageForm,
    setKitchenEquipment,
    setKitchenEquipmentChangeRequests,
    setKitchenEquipmentForm,
    setKitchenEquipmentChangeForm,
    setKitchenEquipmentStatus,
    setSelectedInvestmentSiteId,
    setOpenFormDrawer,
    pendingIssueConfirm,
    setPendingIssueConfirm,
  });

  const {
    filteredSites,
    selectedDetailSite,
    filteredUsageRequests,
    filteredKitchenEquipment,
    filteredKitchenEquipmentChangeRequests,
    selectedDetailSiteData,
    metrics,
    clientParties,
    operatorParties,
    subcontractorParties,
    updateSelectedMaterial,
  } = useProjectSitesWorkspaceModel({
    usageOnly,
    sites,
    usageRequests,
    kitchenEquipment,
    kitchenEquipmentChangeRequests,
    complianceSummaries,
    parties,
    materials,
    query,
    usageFilter,
    selectedDetailSiteId,
    setUsageForm,
  });

  const externalProjectSiteWorkspaceViewProps = buildExternalProjectSiteWorkspaceViewProps({
    portal: buildExternalProjectSitePortalOptions({
      portalSection,
      onPortalSectionChange,
      externalProjectSiteContactName,
      externalProjectSiteContactPhone,
      permissions,
    }),
    data: {
      sites,
      complianceSummaries,
      kitchenEquipment,
      kitchenEquipmentStatus,
      usageStatus,
      masterStatus,
      warehouses,
      materials,
    },
    model: {
      filteredUsageRequests,
      filteredKitchenEquipment,
      filteredKitchenEquipmentChangeRequests,
      metrics,
      updateSelectedMaterial,
    },
    permissions,
    state: {
      query,
      usageFilter,
      openFormDrawer,
      usageForm,
      kitchenEquipmentForm,
      kitchenEquipmentChangeForm,
    },
    submit: {
      usageSubmitState,
      kitchenEquipmentSubmitState,
      kitchenEquipmentChangeSubmitState,
      usageSubmitError,
      kitchenEquipmentSubmitError,
      kitchenEquipmentChangeSubmitError,
    },
    handlers: {
      onOpenForm: setOpenFormDrawer,
      onQueryChange: setQuery,
      onUsageFilterChange: setUsageFilter,
      onUsageFormChange: setUsageForm,
      onKitchenEquipmentFormChange: setKitchenEquipmentForm,
      onKitchenEquipmentChangeFormChange: setKitchenEquipmentChangeForm,
      onCloseForm: closeFormDrawer,
      onCreateUsageRequest: handleCreateUsageRequest,
      onCreateKitchenEquipment: handleCreateKitchenEquipment,
      onCreateKitchenEquipmentChangeRequest: handleCreateKitchenEquipmentChangeRequest,
      onReviewKitchenEquipmentChangeRequest: handleReviewKitchenEquipmentChangeRequest,
    },
  });

  const projectSitesHeadquartersViewProps = buildProjectSitesHeadquartersViewProps({
    data: {
      sites,
      siteStatus,
      complianceSummaries,
      usageRequests,
      usageStatus,
      masterStatus,
      materials,
      warehouses,
      businessProjects,
      investmentSummary,
      investmentSummaryStatus,
      selectedInvestmentSiteId,
      kitchenEquipment,
      kitchenEquipmentStatus,
    },
    model: {
      filteredSites,
      filteredUsageRequests,
      filteredKitchenEquipment,
      filteredKitchenEquipmentChangeRequests,
      selectedDetailSite,
      selectedDetailSiteData,
      metrics,
      clientParties,
      operatorParties,
      subcontractorParties,
      updateSelectedMaterial,
    },
    permissions: {
      canEditSites,
      canCreateUsage,
      canIssueUsage,
    },
    state: {
      query,
      usageFilter,
      openFormDrawer,
      siteForm,
      usageForm,
      issueForm,
      kitchenEquipmentForm,
      kitchenEquipmentChangeForm,
      pendingIssueConfirm,
    },
    submit: {
      siteSubmitState,
      usageSubmitState,
      issueSubmitState,
      kitchenEquipmentSubmitState,
      kitchenEquipmentChangeSubmitState,
      siteSubmitError,
      usageSubmitError,
      issueSubmitError,
      kitchenEquipmentSubmitError,
      kitchenEquipmentChangeSubmitError,
    },
    handlers: {
      onQueryChange: setQuery,
      onUsageFilterChange: setUsageFilter,
      onOpenForm: setOpenFormDrawer,
      onSelectSite: (site) => setSelectedDetailSiteId(site.id),
      onSelectedInvestmentSiteChange: setSelectedInvestmentSiteId,
      onSiteFormChange: setSiteForm,
      onUsageFormChange: setUsageForm,
      onIssueFormChange: setIssueForm,
      onKitchenEquipmentFormChange: setKitchenEquipmentForm,
      onKitchenEquipmentChangeFormChange: setKitchenEquipmentChangeForm,
      onCancelIssueConfirm: () => setPendingIssueConfirm(false),
      onCloseForm: closeFormDrawer,
      onCloseDetail: () => setSelectedDetailSiteId(""),
      onCreateSite: handleCreateSite,
      onCreateUsageRequest: handleCreateUsageRequest,
      onIssueUsageRequest: handleIssueUsageRequest,
      onCreateKitchenEquipment: handleCreateKitchenEquipment,
      onCreateKitchenEquipmentChangeRequest: handleCreateKitchenEquipmentChangeRequest,
      onReviewKitchenEquipmentChangeRequest: handleReviewKitchenEquipmentChangeRequest,
    },
    attachments: {
      loadAttachments: loadUnifiedAttachments,
      getAttachmentDownloadUrl,
    },
  });

  return (
    <section className="project-sites-workspace" aria-label="项目点">
      {usageOnly ? (
        <ExternalProjectSiteWorkspaceView {...externalProjectSiteWorkspaceViewProps} />
      ) : (
        <ProjectSitesHeadquartersView {...projectSitesHeadquartersViewProps} />
      )}
    </section>
  );
}
